<?php

//implement hook_menu()

function custom_menu() {
$items = array();

$items['mycustom']=array(
'title'=>'MyCustom',
'page callback'=>'mycustom_form',
'page arguments' => array('mycustom_form'),
'access arguments' => array('administer mycustom_form'),
 'type' => MENU_NORMAL_ITEM,



);


return $items;
}

function mycustom_form() {

return drupal_get_form('mycustom_form_form1');

}

function mycustom_form_form1($form, &$form_state) {

$form['simple_text']=array(
'#markup' => 'The page is not found',

);

$argval=arg(0);
if($argval=='mycustom'){

$nid=db_insert('custom')
  ->fields(array('name' => $argval))
  ->execute();


}

return $form;
}

